version: '3'
services:
  nginx:
    build: ./nginx
    image: hika1282/nginx:${APACHE_TAG}
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - myNetwork
  apache:
    build: ./apache
    image: hika1282/apache:${APACHE_TAG}
    container_name: apache
    restart: always
    networks:
      - myNetwork

networks:
  myNetwork:
    driver: bridge
